### ISSUE TITLE
reproduce and report Npgsql bug related to command cancellation

### ISSUE THREAD

**Issue by warning-explosive** [warning-explosive/Core#190]
https://stackoverflow.com/questions/32632926/error-57014-canceling-statement-due-to-user-request-npgsql

`Npgsql.NpgsqlException
Exception while reading from stream
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|211_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in /_/Dapper/SqlMapper.Async.cs:line 646
   at NpgsqlRepro.UnitTest1.UpdateEntityConcurrently(Guid primaryKey, Int64 version, TimeSpan delay, AutoResetEvent sync, CancellationToken token) in /Users/nikitagrishin/Git/NpgsqlRepro/UnitTest1.cs:line 333
   at NpgsqlRepro.UnitTest1.Test1() in /Users/nikitagrishin/Git/NpgsqlRepro/UnitTest1.cs:line 73
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90

System.TimeoutException
Timeout during reading attempt
  Exception doesn't have a stacktrace`

**Comment by warning-explosive** [comment]
https://github.com/npgsql/npgsql/issues/4596

**Comment by warning-explosive** [comment]
deadlock made by row-locking mechanism in the db and misusage of synchronization primitive
